AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

# For easier reading of the book while writting this code,
# I'm following its convention which is Java because
# the book code is in Java. So I'll disable the naming rules.
Naming:
  Enabled: false

# For the same reason I won't fiddle with code organisation to get
# smaller methods. I'm following book's code structure which makes
# sense in the context of an interpreter.
Metrics:
  Enabled: false

# The code is intetionally not following idiomatic ruby formatting style
# so that's it's closer to the book's code which is in Java. This is so
# that it's easier to find relevant parts of the book while reading the code.
Style:
  Enabled: false

# One of the tokens is `:true` so this misfires a lot.
Lint/BooleanSymbol:
  Enabled: false
