AllCops:
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

# For easier reading of the book while writting this code,
# I'm following its convention which is Java because
# the book code is in Java. So I'll disable the naming rules.
Naming:
  Enabled: false

# For the same reason I won't fiddle with code organisation to get
# smaller methods. I'm following book's code structure which makes
# sense in the context of an interpreter.
Metrics:
  Enabled: false

# I'm following a book closely with the code, the book is the documentation.
Style/Documentation:
  Enabled: false

