module RubyLox
  class Environment
    attr_reader enclosing: Environment

    def initialize: (?Environment? enclosing) -> void

    def define: (String name, Object? value) -> Object

    def get: (String name) -> (String | Numeric | Interpreter::LoxClass | Interpreter::LoxInstance | nil)

    def getAt: (Integer distance, String name) -> (String | Numeric | Interpreter::LoxClass | Interpreter::LoxInstance | nil)

    def assign: (String name, Object? value) -> void

    def assignAt: (Integer distance, String name, Object? value) -> void

    private

    def fail_undefined: (String name) -> nil
  end
end
