module RubyLox
  # Base error for all compile time errors.
  class LoxCompileError < RuntimeError
    def initialize: (RubyLox::Token token, String message) -> void

    def to_s: () -> ::String
  end

  # Base error for all runtime errors.
  class LoxRuntimeError < RuntimeError
    def initialize: (String message) -> void

    def to_s: () -> ::String
  end
end
